### ISSUE TITLE
Automatically reference/dereference

### ISSUE THREAD

**Issue by Olle-Lukowski** [eliemichel/WebGPU-Cpp#11]
I was wondering if it is within scope to implement RAII destructors, so we can have fully automatic handling of the lifetime of objects?

**Comment by eliemichel** [comment]
This wrapper is meant to have 0 runtime effect/overhead compared to using the raw C API. If you're interested in RAII, you can consult [this chapter](https://eliemichel.github.io/LearnWebGPU/advanced-techniques/raii.html), and also since I had been talking about it for a while I just released the RAII wrapper that I use in practice, although I'm not 100% happy with it: https://github.com/eliemichel/WebGPU-raii

**Comment by Olle-Lukowski** [comment]
alright, thanks for the quick response!
