### ISSUE TITLE
Use [[nodiscard]] on select functions

### ISSUE THREAD

**Issue by goodartistscopy** [eliemichel/WebGPU-Cpp#17]
Hello,

Some `Device` member functions, e.g.:
 `std::unique_ptr<ErrorCallback> popErrorScope(ErrorCallback&& callback);`
and
`std::unique_ptr<ErrorCallback> setUncapturedErrorCallback(ErrorCallback&& callback);`,
could probably use a `[[nodiscard]]` annotation (available in C++ 17), because failure to store the return value results in a crash.

**Comment by eliemichel** [comment]
Oh, this is a good idea indeed!

**Comment by eliemichel** [comment]
Done!

Note that I had disabled the generation of a `Device::popErrorScope` because the callback argument is called "oldCallback" so I thought it had to be the very same pointer as a call to some "push" operation. Turns out that it seems to be a regular callback that just happens to have a different name, so I just reverted it back.

**Comment by goodartistscopy** [comment]
Thanks a lot !

**Comment by goodartistscopy** [comment]
I wonder if it's called oldCallback because they're pushing for the new  Future API
```
WGPU_EXPORT void wgpuDevicePopErrorScope(WGPUDevice device, WGPUErrorCallback oldCallback, void * userdata) WGPU_FUNCTION_ATTRIBUTE;
WGPU_EXPORT WGPUFuture wgpuDevicePopErrorScope2(WGPUDevice device, WGPUPopErrorScopeCallbackInfo2 callbackInfo) WGPU_FUNCTION_ATTRIBUTE;
WGPU_EXPORT WGPUFuture wgpuDevicePopErrorScopeF(WGPUDevice device, WGPUPopErrorScopeCallbackInfo callbackInfo) WGPU_FUNCTION_ATTRIBUTE;
```
